all:
	@echo ""
	@echo "************************************************************"
	@echo "Construindo o cliente...  "
	@echo "************************************************************"
	@echo "" 
	@echo "" 
	make -f Makefile.cliente

	@echo ""
	@echo "************************************************************"
	@echo "Construindo o servidor...  "
	@echo "************************************************************"
	@echo "" 
	@echo ""
	make -f Makefile.servidor

clean:
	@echo ""
	@echo "************************************************************"
	@echo "Limpando os arquivos de compilação do cliente...  "
	@echo "************************************************************"
	@echo "" 
	@echo "" 
	make -f Makefile.cliente clean

	@echo ""
	@echo "************************************************************"
	@echo "Limpando os arquivos de compilação do servidor...  "
	@echo "************************************************************"
	@echo "" 
	@echo "" 
	make -f Makefile.servidor clean	
